"use client";

import { Info, Monitor, Smartphone } from "lucide-react";
import { useDeferredValue, useMemo, useState } from "react";

import type { EditorialMetadata } from "@/lib/editorial/contracts/metadata";
import type { ClaimMarker } from "@/lib/editorial/markdown/render";
import { renderMarkdown } from "@/lib/editorial/markdown/render";
import {
  AUDIENCE_LABELS,
  CATEGORY_LABELS,
  REVENUE_GOAL_LABELS,
  TOOL_LABELS,
  buildTimeLabel,
} from "@/lib/editorial/presentation/metadata-labels";
import { cn } from "@/lib/utils";
import styles from "../editorial.module.css";
import { pressedToggleClass } from "./ui";

export const PREVIEW_ID_PREFIX = "preview";

const NOTICE_LABELS = {
  raw_markup: "Raw markup shown as text",
  unsafe_link: "Link target removed",
  image_not_loaded: "Image not loaded",
  depth_limited: "Nesting flattened",
} as const;

/**
 * Safe editorial preview of the whole publication: metadata, highlights,
 * body and social-card inputs. It is not the public renderer, and says so.
 */
export function PreviewPane({
  title,
  markdown,
  metadata,
  claims,
  onClaim,
}: {
  title: string;
  markdown: string;
  metadata: EditorialMetadata;
  claims: ClaimMarker[];
  onClaim(claimId: string): void;
}) {
  const [mode, setMode] = useState<"desktop" | "mobile">("desktop");
  const deferred = useDeferredValue(markdown);
  const rendered = useMemo(
    () => renderMarkdown(deferred, { claims, onClaim, idPrefix: PREVIEW_ID_PREFIX }),
    [deferred, claims, onClaim],
  );

  return (
    <div className="flex flex-col gap-4">
      <p className="flex items-start gap-2 rounded-md border border-(--ed-info) bg-(--ed-info-bg) px-3 py-2 text-sm text-(--ed-info)">
        <Info aria-hidden="true" className="mt-0.5 size-4 shrink-0" />
        <span>
          <strong className="font-semibold">Editorial preview — public rendering not yet verified.</strong> Raw HTML, MDX
          and scripts appear as text and images are not fetched. Claim markers open their evidence.
        </span>
      </p>
      <div role="group" aria-label="Preview width" className="flex gap-2">
        <button type="button" aria-pressed={mode === "desktop"} className={pressedToggleClass} onClick={() => setMode("desktop")}>
          <Monitor aria-hidden="true" className="size-4" />
          Desktop
        </button>
        <button type="button" aria-pressed={mode === "mobile"} className={pressedToggleClass} onClick={() => setMode("mobile")}>
          <Smartphone aria-hidden="true" className="size-4" />
          Mobile (390px)
        </button>
      </div>

      <div className={cn(mode === "mobile" && "mx-auto w-full max-w-[390px]")}>
        <article
          aria-labelledby="preview-title"
          className={cn(
            styles.article,
            "rounded-lg border border-(--ed-border) bg-(--ed-surface)",
            mode === "mobile" ? "px-4 py-5 text-base" : "px-5 py-6 sm:px-8",
          )}
        >
          <header className="mb-6 flex flex-col gap-3">
            <p className="m-0! text-sm text-(--ed-text-2)">
              {CATEGORY_LABELS[metadata.category]} · Build in {buildTimeLabel(metadata.buildTime)} ·{" "}
              {REVENUE_GOAL_LABELS[metadata.revenueGoal]}
            </p>
            <h2 id="preview-title" className="mt-0! mb-0! text-[1.75rem]! leading-tight">
              {title || "Untitled idea"}
            </h2>
            <p className="m-0! text-lg text-(--ed-text-2)">{metadata.description}</p>
            <ul aria-label="Tags" className="m-0! flex list-none! flex-wrap gap-1.5 pl-0!">
              {[...metadata.tools.map((tool) => TOOL_LABELS[tool]), ...metadata.audiences.map((audience) => AUDIENCE_LABELS[audience])].map(
                (label) => (
                  <li key={label} className="m-0! rounded border border-(--ed-border-strong) px-2 py-0.5 text-xs">
                    {label}
                  </li>
                ),
              )}
            </ul>
          </header>

          <HighlightsPreview metadata={metadata} />

          {rendered.node}
        </article>
      </div>

      <section aria-labelledby="preview-social" className="rounded-lg border border-(--ed-border) bg-(--ed-surface) px-4 py-3 text-sm">
        <h3 id="preview-social" className="font-semibold">
          Social card
        </h3>
        {metadata.og ? (
          <p className="mt-1">
            Subject: <span className="font-medium">{metadata.og.subject}</span> · accent{" "}
            <span className="font-mono">{metadata.og.accent}</span>
          </p>
        ) : (
          <p className="mt-1 text-(--ed-text-2)">No social card inputs yet.</p>
        )}
        <p className="mt-1 text-(--ed-text-2)">The image itself is generated by the release pipeline and is not available in the local demo.</p>
      </section>

      {rendered.notices.length > 0 ? (
        <section aria-labelledby="preview-notes" className="rounded-lg border border-(--ed-warning) bg-(--ed-warning-bg) px-4 py-3 text-sm text-(--ed-warning)">
          <h3 id="preview-notes" className="font-semibold">
            Preview notes ({rendered.notices.length})
          </h3>
          <ul className="mt-1 list-disc pl-5">
            {rendered.notices.slice(0, 50).map((notice, index) => (
              <li key={`${notice.kind}-${notice.line ?? "x"}-${index}`}>
                {NOTICE_LABELS[notice.kind]}
                {notice.line ? ` (line ${notice.line})` : ""}: {notice.detail}
              </li>
            ))}
          </ul>
        </section>
      ) : null}
    </div>
  );
}

function HighlightsPreview({ metadata }: { metadata: EditorialMetadata }) {
  const highlights = metadata.highlights;
  if (!highlights) {
    return <p className="rounded-md border border-dashed border-(--ed-border-strong) px-3 py-2 text-sm text-(--ed-text-2)">No homepage highlights.</p>;
  }
  return (
    <section aria-labelledby="preview-highlights" className="mb-8 rounded-lg border border-(--ed-border) bg-(--ed-canvas) px-4 py-4 text-[0.9375rem]">
      <h3 id="preview-highlights" className="mt-0! text-sm! uppercase tracking-wide text-(--ed-text-2)">
        Homepage highlights
      </h3>
      <blockquote className="mb-3!">“{highlights.problemQuote}”</blockquote>
      <dl className="grid gap-3 sm:grid-cols-3">
        {highlights.stats.map((stat) => (
          <div key={`${stat.value}-${stat.label}`}>
            <dt className="font-mono text-lg font-semibold">{stat.value}</dt>
            <dd className="text-sm">
              {stat.label}
              {stat.source ? <span className="block text-xs text-(--ed-text-2)">Source: {stat.source}</span> : null}
            </dd>
          </div>
        ))}
      </dl>
      {highlights.competitors ? (
        <>
          <h4 className="text-sm! font-semibold">Competitor prices</h4>
          <ul className="m-0! flex list-none! flex-wrap gap-2 pl-0!">
            {highlights.competitors.map((competitor) => (
              <li key={competitor.name} className="m-0! rounded border border-(--ed-border-strong) bg-(--ed-surface) px-2 py-0.5 text-sm">
                {competitor.name} <span className="font-mono">{competitor.price}</span>
              </li>
            ))}
          </ul>
        </>
      ) : null}
      {highlights.tiers ? (
        <>
          <h4 className="text-sm! font-semibold">Proposed pricing tiers</h4>
          <ul className="m-0! flex list-none! flex-wrap gap-2 pl-0!">
            {highlights.tiers.map((tier) => (
              <li key={tier.name} className="m-0! rounded border border-(--ed-border-strong) bg-(--ed-surface) px-2 py-0.5 text-sm">
                {tier.name} <span className="font-mono">{tier.price}</span>
              </li>
            ))}
          </ul>
        </>
      ) : null}
    </section>
  );
}
