import type { ActivityAction } from "../contracts/views";

export const ACTIVITY_LABELS: Record<ActivityAction, string> = {
  "submission.imported": "Submission imported",
  "submission.rejected": "Submission refused",
  "revision.created": "Revision created",
  "revision.saved": "Draft saved",
  "revision.discarded": "Draft discarded",
  "candidate.decided": "Candidate decision",
  "review.attested": "Marked reviewed",
  "review.retracted": "Review withdrawn",
  "review.flagged": "Discrepancy flagged",
  "review.resolved": "Issue resolved",
  "review.changes_requested": "Changes requested",
  "review.resumed": "Review resumed",
  "note.added": "Note added",
  "checks.run": "Checks run",
  "approval.granted": "Revision approved",
  "approval.revoked": "Approval revoked",
  "release.prepared": "Preview staged",
  "release.requested": "Publish confirmed",
  "release.advanced": "Release step",
  "release.failed": "Release failed",
  "release.cancelled": "Release cancelled",
  "release.retried": "Release retried",
  "release.reconciled": "Release reconciled",
  "release.succeeded": "Release succeeded",
  "rollback.requested": "Rollback requested",
  "unpublish.requested": "Unpublished",
  "idea.trashed": "Moved to Trash",
  "idea.restored": "Restored from Trash",
  "settings.changed": "Settings changed",
  "access.denied": "Access denied",
};
